cors:
  global:
    origins: >
      https://marketplace.dev.merlot-education.eu,
      https://api.dev.merlot-education.eu,
      https://cif.dev.merlot-education.eu
    patterns:

merlot-domain: "marketplace.dev.merlot-education.eu"

server:
  ssl:
    enabled: false # will be set by cluster
  http:
    port: 0