cors:
  global:
    origins: >
      https://marketplace.demo.merlot-education.eu,
      https://api.demo.merlot-education.eu,
      https://cif.demo.merlot-education.eu
    patterns:

did-domain: "marketplace.demo.merlot-education.eu"

server:
  port: 8088 # with ssl disabled this will be the http port
  ssl:
    enabled: false # will be set by cluster
  http:
    port: 0 # disable other ports